### ISSUE TITLE
Data is not receiving using this python script EXbee/examples/receive_EXbee.py

### ISSUE THREAD

**Issue by titusece** [esmairi/EXbee#1]
Hi,
I'm not able to receive the data first time using "receive_EXbee" python script  and getting the data when I run the send script for second time.

Termina1:
sudo python EXbee_Rpi/examples/receive_EXbee.py

Terminal2:
sudo python EXbee_Rpi/examples/receive_EXbee.py
Not getting the data in terminal1.

sudo python EXbee_Rpi/examples/receive_EXbee.py
Now received the data in terminal1.

I'm sure that send script doesn't have any problem while sending ?
What could be the problem in receive python script ?

**Comment by esmairi** [comment]
Make sure you have correctly configured the Xbee that it can send and receive in both direction, you check by sending and receive data using xctu

**Comment by titusece** [comment]
Thanks for the reply.
I have checked the settings and I am not able to see any settings for bi-directional transfer (I hope by default, its set to bi-directional)

Terminal2:
sudo python EXbee_Rpi/examples/send_EXbee.py
( control + c) i.e quit
sudo python EXbee_Rpi/examples/send_EXbee.py

Termina1:
sudo python EXbee_Rpi/examples/receive_EXbee.py
Not getting the data for the first send

"Hi"
Now got the data for the second send script....

**Comment by esmairi** [comment]
i mean the configuration of your Xbee(coordiantor , router, end device ) and the DL and DH,
follow this steps: http://jesmairi.blogspot.com/2016/07/this-tutorial-is-to-explain-how-to-use.html
